"""initial coffee journal

Revision ID: b261b9a424ce
Revises: 
Create Date: 2022-03-05 16:36:57.848994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b261b9a424ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_datetime', sa.DateTime(), nullable=True),
    sa.Column('coffee_name', sa.Unicode(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('flavor_notes', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('example_1', sa.String(length=255), nullable=True),
    sa.Column('example_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_model_example_2'), 'example_model', ['example_2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_model_example_2'), table_name='example_model')
    op.drop_table('example_model')
    op.drop_table('coffee_journal')
    # ### end Alembic commands ###
